---

services:
  # docker: mvdan/shfmtは作者製
  # https://hub.docker.com/r/mvdan/shfmt/dockerfile
  fmt-sh:
    image: mvdan/shfmt:v3.12.0
    command: ['-i', '2', '-w', './scripts/']
    working_dir: /works/
    volumes:
      - type: bind
        source: ${PWD}/
        target: /works/

  # docker: koalaman/shellcheck は作者製
  # https://hub.docker.com/r/koalaman/shellcheck
  lint-sh:
    image: koalaman/shellcheck:v0.11.0
    working_dir: /works/
    volumes:
      - type: bind
        source: ${PWD}/
        target: /works/
